version: '3'

services:

  mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet



  web:
    build: .
    image: codenar_web
    env_file:
      - .env
      - .version
    command: bash -c "gunicorn -c gunicorn.conf --log-level INFO --reload -b 0.0.0.0:8000 config.wsgi"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - DJANGO_READ_DOT_ENV_FILE=true
      - PGHOST=db
      - PYTHONDONTWRITEBYTECODE=true

  redis:
    image: "redis:alpine"

volumes:
  postgres_data:
