version: '3'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=codenar
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    image: codenar_web
    env_file:
      - .env
      - .version
    command: bash -c "gunicorn -c gunicorn.conf --log-level INFO --reload -b 0.0.0.0:8000 config.wsgi"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_READ_DOT_ENV_FILE=true
      - PGHOST=db
      - PYTHONDONTWRITEBYTECODE=true

  redis:
    image: "redis:alpine"

volumes:
  postgres_data:
